name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  upload-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload Pages artifact (docs)
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs'

  deploy-pages:
    needs: upload-pages
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1